{% set name = "traceback-with-variables" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3be6c0e48a671ef50590aa699cfa799eb956cd3eff21080c6a01d244c06f2f86

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - traceback-with-variables = traceback_with_variables.main:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  commands:
    - traceback-with-variables --help
  imports:
    - traceback_with_variables

about:
  home: https://github.com/andy-landy/traceback_with_variables
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Traceback (Error Message) Printing Variables.
  description: |
    Very simple to use, but versatile when needed.  Try for
    debug and keep for production.Adds variables to python
    traceback. Simple, lightweight,
    controllable. Debug reasons of exceptions by logging or
    pretty printing colorful variable contexts for each frame
    in a stacktrace, showing every value. Dump locals
    environments after errors to console, files, and loggers.
  doc_url: https://github.com/andy-landy/traceback_with_variables/blob/master/README.md
  dev_url: https://github.com/andy-landy/traceback_with_variables

extra:
  recipe-maintainers:
    - andy-landy
