{% set name = "traceback-with-variables" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a30c79b7c206fb255967f3f5d125ce114b3dae4fd92d268f901dd35ee23f9cc0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - traceback-with-variables = traceback_with_variables.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - traceback-with-variables --help
  imports:
    - traceback_with_variables

about:
  home: https://github.com/andy-landy/traceback_with_variables
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Traceback (Error Message) Printing Variables.
  description: |
    Very simple to use, but versatile when needed.  Try for
    debug and keep for production.Adds variables to python
    traceback. Simple, lightweight,
    controllable. Debug reasons of exceptions by logging or
    pretty printing colorful variable contexts for each frame
    in a stacktrace, showing every value. Dump locals
    environments after errors to console, files, and loggers.
  doc_url: https://github.com/andy-landy/traceback_with_variables/blob/master/README.md
  dev_url: https://github.com/andy-landy/traceback_with_variables

extra:
  recipe-maintainers:
    - andy-landy
